-- -------------------------------------------------------------
-- 
-- File Name: /home/apurvan/BBU/qpskprj/hdlsrc/nrhdlSymbolModulatorModel/NR_Symbol_Modulator.vhd
-- Created: 2020-01-24 17:38:16
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- dataOut_re                    ce_out        1
-- dataOut_im                    ce_out        1
-- validOut                      ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: NR_Symbol_Modulator
-- Source Path: nrhdlSymbolModulatorModel/NR Symbol Modulator
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY NR_Symbol_Modulator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        dataIn                            :   IN    std_logic;
        validIn                           :   IN    std_logic;
        modSel                            :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        load                              :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        dataOut_re                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        dataOut_im                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        validOut                          :   OUT   std_logic
        );
END NR_Symbol_Modulator;


ARCHITECTURE rtl OF NR_Symbol_Modulator IS

  -- Component Declarations
  COMPONENT NR_Symbol_Modulator_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          data                            :   IN    std_logic;
          valid                           :   IN    std_logic;
          data1_re                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          data1_im                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          valid1                          :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : NR_Symbol_Modulator_block
    USE ENTITY work.NR_Symbol_Modulator_block(rtl);

  -- Signals
  SIGNAL data_re                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL data_im                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL valid                            : std_logic;

BEGIN
  u_NR_Symbol_Modulator : NR_Symbol_Modulator_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              data => dataIn,
              valid => validIn,
              data1_re => data_re,  -- sfix16_En14
              data1_im => data_im,  -- sfix16_En14
              valid1 => valid
              );

  ce_out <= clk_enable;

  dataOut_re <= data_re;

  dataOut_im <= data_im;

  validOut <= valid;

END rtl;

