-- -------------------------------------------------------------
-- 
-- File Name: /home/apurvan/BBU/qpskprj/hdlsrc/nrhdlSymbolModulatorModel/NR_Symbol_Modulator_pkg.vhd
-- Created: 2020-01-24 17:38:16
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE NR_Symbol_Modulator_pkg IS
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
END NR_Symbol_Modulator_pkg;

